---



- name: destroy ASG
  ec2_asg:
    name: "{{ nxl_env_name }}_asg"
    state: absent
    region: ap-southeast-2
    wait_for_instances: false



# Create ELB  for exposing NXL to internet and attach a listener with logging enabled
- name: Destroy load balancer
  elb_application_lb:
    region: ap-southeast-2
    name: "{{ nxl_env_name }}-elb"
    state: absent
    wait: True

- pause:
    minutes: 1

# Create a target group with targets
- name: Destroy target group
  elb_target_group:
    region: ap-southeast-2
    name: "{{ nxl_env_name }}-tg"
    state: absent
    wait: True

